### ISSUE TITLE
Try script never exits on long provider chains

### ISSUE THREAD

**Issue by tkmcmaster** [FamilySearch/pewpew#123]
## Describe the bug
Try script never exits on long provider chains

## Expected behavior
Try script should exit once all endpoints have run once (or the one specified by -i)

## Config file

```yaml
providers:
  a:
    range: {}
  b:
    response: {}
  c:
    response: {}
  d:
    response: {}
  e:
    response: {}
  f:
    response: {}

load_pattern:
  - linear:
      from: 100%
      to: 100%
      over: 5s

loggers:
  test:
    to: stderr

vars:
  port: "${PORT}"


endpoints:
  - method: POST
    url: http://localhost:${port}
    body: '{"a": ${a}}'
    provides:
      b:
        select: response.body.a
    on_demand: true

  - method: POST
    url: http://localhost:${port}
    body: '{"b": ${b}}'
    provides:
      c:
        select: response.body.b
    on_demand: true

  - method: POST
    url: http://localhost:${port}
    body: '{"c": ${c}}'
    provides:
      d:
        select: response.body.c
    on_demand: true

  - method: POST
    url: http://localhost:${port}
    body: '{"d": ${d}}'
    provides:
      e:
        select: response.body.d
    on_demand: true

  - method: POST
    url: http://localhost:${port}
    body: '{"e": ${e}}'
    provides:
      f:
        select: response.body.e
    on_demand: true

  - method: POST
    url: http://localhost:${port}
    body: '{"f": ${f}}'
    peak_load: 1hps
    logs:
      test:
        select: response.body.f
```

## Command to run
*Enter below the full command used to execute Pewpew.*

```sh
PORT=8084 test-server &

PORT=8084 pewpew try tests/provider_chain.yaml
or
PORT=8084 pewpew try tests/provider_chain.yaml -i _id=5
```

## System info
 - Operating System: "Ubuntu 20.04"
 - Pewpew version: pewpew 0.5.12

## Additional context
Checking old versions, it last worked in 0.5.7 and has been broken in 0.5.8 forward. It will run in `pewpew run`, but hangs on `pewpew try`
