### ISSUE TITLE
pewpew 5.6 beta5 preview 4 exits immediately

### ISSUE THREAD

**Issue by tkmcmaster** [FamilySearch/pewpew#17]
## Describe the bug
Running the new pewpew v.0.5.6 beta 5 preview 4 exits immediately on a 2 minute test without running anything. A try script works fine.

## Expected behavior
Test should run

## Config file

```yaml
vars:
  rampTime: 1m
  loadTime: 1m
  totalTime: 2m
  serviceUrlAgent: ${SERVICE_URL_AGENT}
load_pattern:
  - linear:
      from: 1%
      to: 100%
      over: ${rampTime}
  - linear:
      from: 100%
      to: 100%
      over: ${loadTime}
config:
  client:
    headers:
      TestTime: '${epoch("ms")}'
      Accept: application/json
      FS-User-Agent-Chain: Performance Test
      User-Agent: Performance Test
  general:
    bucket_size: 1m
    log_provider_stats: 1m
endpoints:
  - method: GET
    url: http://${serviceUrlAgent}/healthcheck
    peak_load: 30hpm
```

## Command to run

```sh
# export SERVICE_URL_AGENT="127.0.0.1:8080"
# pewpew run -w -f json createtest.yaml

or 

# pewpew run createtest.yaml
```

## System info
 - Operating System: Ubuntu 18.04 and Windows 10
 - Pewpew version: pewpew 0.5.6-beta5-preview-4

## Additional context
Output from run or run -f json
```
{"type":"start","msg":"Test will end around 10:42:20 26-Jun-2020 in approximately 2 minutes","binVersion":"0.5.6-beta5-preview-4"}

OR

Starting load test. Test will end around 10:42:59 26-Jun-2020 in approximately 2 minutes

Test Summary 10:40:00 to 10:41:00 26-Jun-2020
no data

Test Summary 10:40:59 to 10:42:59 26-Jun-2020
no data
```

**Comment by EliSnow** [comment]
Further reduced test case:

```
load_pattern:
  - linear:
      from: 1%
      to: 100%
      over: 1m
endpoints:
  - method: GET
    url: http://127.0.0.1:8080
    peak_load: 30hpm
```

It appears to be the `from: 1%` in the load pattern causing the issue. Removing that, or changing it to an explicit `from: 0%` does not manifest the bug. Alternatively, changing the `over` to `over: 4m` does not manifest the bug.
