### ISSUE TITLE
File Bodies no longer work after 0.5.6 beta 4

### ISSUE THREAD

**Issue by tkmcmaster** [FamilySearch/pewpew#35]
## Describe the bug
File body's do not send the correct data and fail. I get timeouts or 504 from the server I'm testing, and the test-server just hangs and never responds.

## Expected behavior
Using a file body in place of a string body should work seamlessly

## Config file

```yaml
vars:
  port: ${PORT}
load_pattern:
  - linear:
      from: 100%
      to: 100%
      over: 5m
config:
  client:
    headers:
      Accept: '*/*'
  general:
    bucket_size: 1m
    log_provider_stats: 1m
endpoints:
  ###### PUT text ######
  - method: PUT
    url: 'http://localhost:${port}/'
    tags:
      type: put-text
      status: ${response.status}
    headers:
      Content-Type: 'text/plain'
    body: 'This is only a test'
    peak_load: 5hpm
  ###### PUT text ######
  - method: PUT
    url: 'http://localhost:${port}/'
    tags:
      type: put-text-file
      status: ${response.status}
    headers:
      Content-Type: 'text/plain'
    body:
      file: 'dist.txt'
    peak_load: 5hpm
```

dist.txt:
```
This is only a test
```
## Command to run

```sh
$ PORT=8080 test-server &
$ pewpew try FileTest.yaml -i _id=0
$ pewpew try FileTest.yaml -i _id=1
```

## System info
 - Operating System: Windows 10
 - Pewpew version: 0.5.7 and 0.5.8 preview 1

## Additional context
It worked in 0.5.5, and 0.5.6 beta 1-4.
0.5.6 beta 5 on and 0.5.7 just hang. But 0.5.8 preview 1 returns this error from the test-server:

```
Request
========================================
PUT / HTTP/1.1
accept: */*
content-type: text/plain
host: localhost
content-length: 19

<<contents of file: dist.txt>>

Response (RTT: nullms)
========================================
null
null

null
```
