### ISSUE TITLE
ON_DEMAND does not work

### ISSUE THREAD

**Issue by summersjc** [FamilySearch/pewpew#46]
## Describe the bug
*A clear and concise description of what the bug is.*
ON_DMAND : true does not seem to be working in the latest version of pewpew
## Expected behavior
*A clear and concise description of what you expected to happen.*
on demand should run as often as the provider is needed 
## Config file
*Paste your [simplified config file](https://familysearch.github.io/pewpew/bug-report.html) below.*
https://github.com/fs-eng/SystemTestTools/blob/master/pewpewtests/Membership/UnitOnly.yaml
```yaml
providers:
  a:
    response: {}

load_pattern:
  - linear:
      from: 100%
      to: 100%
      over: 5s

loggers:
  test:
    to: stderr

vars:
  port: "${PORT}"


endpoints:
  - url: http://localhost:${port}
    peak_load: 1hps
    provides:
      a:
        select: 1
    on_demand: true
    
  - url: http://localhost:${port}?${a}
    logs:
      test:
        select: 1
```
Here is simplified version of issue https://github.com/fs-eng/SystemTestTools/blob/master/pewpewtests/Membership/UnitOnlyBUGREPRODUCEONDEMAND.yaml

## Command to run
*Enter below the full command used to execute Pewpew.*

```sh
# command here
./pewpew run UnitOnlyBUGREPRODUCEONDEMAND.yaml -w
```

## System info
 - Operating System: Linux
 - Pewpew version: 0.5.8 preview 3 from `pewpew --version`*
Seems to work on preview 2
