### ISSUE TITLE
Config Parser "unreachable" error when logger filename has epoch

### ISSUE THREAD

**Issue by tkmcmaster** [FamilySearch/pewpew#50]
## Describe the bug
Trying to parse a yaml file that has a logger filename with an `epoch` expression in it causes the config parser to throw an "unreachable" error

## Expected behavior
The file works fine running in pewpew, it's purely a bug in the config parser. The file should parse

## Config file

```yaml
load_pattern:
  - linear:
      from: 100%
      to: 100%
      over: 5s
loggers:
  timeLogger:
    to: 'test-${epoch("ms")}.csv'
endpoints:
  - method: GET
    url: http://localhost:8082
    peak_load: 1hps
```

## Command to run
This is a bug in the config parser. Try to load the yaml file in the config parser.

## System info
 - Operating System: Ubuntu, Windows 10
 - Pewpew version: 0.5.7 and 0.5.8-preview4

## Additional context
We can currently work around this by clicking the "Bypass Config Parser" in PPaaS.

Stack trace:
```
Error loading config RuntimeError: unreachable
    at __rust_start_panic (wasm-function[23713]:0x5f2664)
    at rust_panic (wasm-function[21760]:0x5e4bc9)
    at std::panicking::rust_panic_with_hook::h4f753dc70b771d8e (wasm-function[4997]:0x44ce68)
    at std::panicking::begin_panic::{{closure}}::hce5f3f65f96f2f2a (wasm-function[21731]:0x5e4765)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h706c23cb5ca53ba5 (wasm-function[21065]:0x5dd646)
    at std::panicking::begin_panic::h500a2937ff20cfd7 (wasm-function[21729]:0x5e4705)
    at std::sys::wasm::time::SystemTime::now::h780c8e91d0f652ad (wasm-function[23571]:0x5f20d9)
    at std::time::SystemTime::now::h92037ca9d5c1afb7 (wasm-function[23679]:0x5f2598)
    at config::expression_functions::Epoch::evaluate::h6570f5e8899733b3 (wasm-function[508]:0x224ec8)
    at config::select_parser::FunctionCall::evaluate::h45d43120f81d82c2 (wasm-function[121]:0x126ccc)
```
